---
kind: pipeline
name: node-10.15.3

steps:
  - name: test
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint generic/Dockerfile

  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: generic/Dockerfile
      target: "base"
      repo: cubyn/node
      tags:
        - "10.15.3"
        - "10.15"
        - "10"
        - "latest"
      build_args:
        - SRC_TAG=10.15.3-alpine
    when:
      event:
        - push
        - pull_request
        - tag
      branch:
        - master

  - name: build_ci
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: generic/Dockerfile
      target: "ci"
      repo: cubyn/node
      tags:
        - "ci-10.15.3"
        - "ci-10.15"
        - "ci-10"
        - "ci-latest"
      build_args:
        - SRC_TAG=10.15.3-alpine
    when:
      event:
        - push
        - pull_request
        - tag
      branch:
        - master

---
kind: pipeline
name: node-11.11.0

steps:
  - name: test
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint generic/Dockerfile

  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: generic/Dockerfile
      target: "base"
      repo: cubyn/node
      tags:
        - "11.11.0"
        - "11.11"
        - "11"
      build_args:
        - SRC_TAG=11.11.0-alpine
    when:
      event:
        - push
        - pull_request
        - tag
      branch:
        - master

  - name: build_ci
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: generic/Dockerfile
      target: "ci"
      repo: cubyn/node
      tags:
        - "ci-11.11.0"
        - "ci-11.11"
        - "ci-11"
      build_args:
        - SRC_TAG=11.11.0-alpine
    when:
      event:
        - push
        - pull_request
        - tag
      branch:
        - master
