kind: pipeline
name: default

steps:
  - name: test
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint generic/Dockerfile

  - name: build
    image: plugins/docker
    settings:
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
      dockerfile: generic/Dockerfile
      target: "base"
      repo: cubyn/node
      tags:
        - "10.15.2"
        - "10.15"
        - "10"
      build_args:
        - SRC_TAG=10.15.2-alpine
    when:
      event:
        - push
        - pull_request
        - tag
      branch:
        - master

  - name: build_latest
    image: plugins/docker
    settings:
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
      dockerfile: generic/Dockerfile
      target: "base"
      repo: cubyn/node
      tags:
        - "latest"
      build_args:
        - SRC_TAG=10.15.2-alpine
    when:
      event:
        - push
        - pull_request
        - tag
      branch:
        - master

  - name: build_ci
    image: plugins/docker
    settings:
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
      dockerfile: generic/Dockerfile
      target: "ci"
      repo: cubyn/node
      tags:
        - "ci-10.15.2"
        - "ci-10.15"
        - "ci-10"
      build_args:
        - SRC_TAG=10.15.2-alpine
    when:
      event:
        - push
        - pull_request
        - tag
      branch:
        - master

  - name: build_ci_latest
    image: plugins/docker
    settings:
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
      dockerfile: generic/Dockerfile
      target: "ci"
      repo: cubyn/node
      tags:
        - "ci-latest"
      build_args:
        - SRC_TAG=10.15.2-alpine
    when:
      event:
        - push
        - pull_request
        - tag
      branch:
        - master
