matrix:
  include:
    # Node JS 10.15
    - NODE_MAJOR: 10
      NODE_MINOR: 15
      NODE_PATCH: 2
      LATEST: "true"
    # Node JS 11.10
    - NODE_MAJOR: 11
      NODE_MINOR: 10
      NODE_PATCH: 1
      LATEST: "false"

pipeline:
  test:
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint generic/Dockerfile

  build:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    dockerfile: generic/Dockerfile
    target: "base"
    repo: cubyn/node
    tags:
      - "${NODE_MAJOR}.${NODE_MINOR}.${NODE_PATCH}"
      - "${NODE_MAJOR}.${NODE_MINOR}"
      - "${NODE_MAJOR}"
    build_args:
      - SRC_TAG=${NODE_MAJOR}.${NODE_MINOR}.${NODE_PATCH}-alpine
    when:
      event: [push, tag, deployment]
      branch: master

  build_latest:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    dockerfile: generic/Dockerfile
    target: "base"
    repo: cubyn/node
    tags:
      - "latest"
    build_args:
      - SRC_TAG=${NODE_MAJOR}.${NODE_MINOR}.${NODE_PATCH}-alpine
    when:
      event: [push, tag, deployment]
      branch: master
      matrix:
        LATEST: "true"

  build_ci:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    dockerfile: generic/Dockerfile
    target: "ci"
    repo: cubyn/node
    tags:
      - "ci-${NODE_MAJOR}.${NODE_MINOR}.${NODE_PATCH}"
      - "ci-${NODE_MAJOR}.${NODE_MINOR}"
      - "ci-${NODE_MAJOR}"
    build_args:
      - SRC_TAG=${NODE_MAJOR}.${NODE_MINOR}.${NODE_PATCH}-alpine
    when:
      event: [push, tag, deployment]
      branch: master

  build_ci_latest:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    dockerfile: generic/Dockerfile
    target: "ci"
    repo: cubyn/node
    tags:
      - "ci-latest"
    build_args:
      - SRC_TAG=${NODE_MAJOR}.${NODE_MINOR}.${NODE_PATCH}-alpine
    when:
      event: [push, tag, deployment]
      branch: master
      matrix:
        LATEST: "true"
